build_support: fix cross-compilation error when CC is a multi-part command
Fix the following error when cross-compiling with an environment-defined CC
that includes flags:

FileNotFoundError: [Errno 2] No such file or directory: 'x86_64-wrs-linux-gcc
-m64 -march=nehalem -mtune=generic -mfpmath=sse -msse4.2
-fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security
-Werror=format-security
--sysroot=/build-1.3.0/tmp/work/corei7-64-wrs-linux/python3-posix-ipc/1.3.0/recipe-sysroot'

This happened because the CC environment variable was treated as a single
string instead of being split into arguments. The fix uses shlex.split() to
correctly parse CC into a list of compiler and flags, and then unpacks it when
forming the subprocess command.

Signed-off-by: Haixiao Yan <haixiao.yan.cn@windriver.com>